sudo: false

services:
  - docker

language: bash

before_install:
  - docker info
  - VERSION="$TRAVIS_BRANCH" make build

after_success:
  - cd ..
  - if [[ "$TRAVIS_TAG" == "$LATEST"* ]]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    VERSION="$TRAVIS_TAG" make tag_latest;
    VERSION="latest" make release_latest;
    fi
