sudo: required

services:
  - docker

script:
  - docker build appium/appium-docker-android .
  - docker run -d appium/appium-docker-android
  - docker ps -a
  - docker run appium/appium-docker-android /bin/sh -c "appium-doctor --android"
  - docker run appium/appium-docker-android /bin/sh -c "android list"
