sudo: false

services:
  - docker

language: bash

before_install:
  - docker -v

script:
  - docker build -t "appium/appium:latest" --build-arg SDK_VERSION=$SDK_VERSION --build-arg ANDROID_BUILD_TOOLS_VERSION=$ANDROID_BUILD_TOOLS_VERSION --build-arg APPIUM_VERSION=$APPIUM_VERSION  -f Appium/Dockerfile .
  - docker run --rm -v $PWD/Appium/tests:/root/tests "appium/appium:latest" bash tests/run-bats.sh
  - docker images

after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ "$TRAVIS_TAG" != "" ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag "appium/appium:latest" "appium/appium:$TRAVIS_TAG" && docker push "appium/appium:$TRAVIS_TAG" && docker push "appium/appium:latest" ;
    fi
