sudo: required

services:
  - docker

script:
  - docker build -t appium .
  - docker run -d appium
  - docker ps -a
  - docker run appium /bin/sh -c "appium-doctor --android"
  - docker run appium /bin/sh -c "android list"
  - docker run appium /bin/sh -c "adb devices"
